FLASK/app/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from .forms import RegistrationForm, LoginForm, CustomerRegistrationForm, UserRegistrationForm, VehicleStatusForm, VehicleUpdateForm
from .models import User, Customer, Vehicle
from . import db, bcrypt
import qrcode
from io import BytesIO
import base64
from sqlalchemy.exc import IntegrityError
from rpa import send_whatsapp_message, build_message  # Importar la función del archivo rpa.py
from datetime import datetime

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template('index.html')

@main.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Su Cuenta fue Creada con Exito!, Puede Iniciar Sesion', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            if user.role == 'operator':
                return redirect(url_for('main.register_customer'))
            elif user.role == 'admin':
                return redirect(url_for('main.admin_dashboard'))
            return redirect(url_for('main.home'))
        else:
            flash('Inicio de sesión sin éxito. Por favor revisa el correo electrónico y la contraseña', 'danger')
    return render_template('login.html', title='Login', form=form)

@main.route('/logout')
def logout():
    logout_user()
    flash('Has Cerrado Sesión Correctamente.', 'info')
    return redirect(url_for('main.home'))

def get_customer_by_document(document):
    return Customer.query.filter_by(document=document).first()

@main.route('/verificar_cliente', methods=['POST'])
@login_required
def verificar_cliente():
    data = request.get_json()
    documento = data.get('documento')
    customer = get_customer_by_document(documento)
    if customer:
        response = {
            'existe': True,
            'cliente': {
                'nombre': customer.name,
                'last_name': customer.last_name,
                'phone': customer.phone
            }
        }
    else:
        response = {'existe': False}
    return jsonify(response)

def get_customer_by_document(document):
    return Customer.query.filter_by(document=document).first()

def get_vehicle_by_license_plate(license_plate):
    return Vehicle.query.filter_by(license_plate=license_plate).first()

@main.route('/register_customer', methods=['GET', 'POST'])
@login_required
def register_customer():
    if current_user.role not in ['admin', 'operator']:
        return redirect(url_for('main.home'))

    form = CustomerRegistrationForm()
    qr_img_base64 = None
    customer = None

    if request.method == 'POST' and 'submit' in request.form and form.validate():
        document = form.customer_document.data
        license_plate = form.vehicle_license_plate.data

        customer = get_customer_by_document(document)
        vehicle = get_vehicle_by_license_plate(license_plate)

        if customer:
            flash('Cliente encontrado.', 'info')
            if vehicle:
                flash('Vehículo encontrado. Se registrará una nueva entrada para el vehículo.', 'info')
                # Registrar nuevo vehículo con la misma placa pero nueva fecha
                new_vehicle = Vehicle(
                    model=form.vehicle_model.data,
                    license_plate=form.vehicle_license_plate.data,
                    vehicle_color=form.vehicle_color.data,
                    vehicle_type=form.vehicle_type.data,
                    customer_id=customer.id,
                    aseguradora=form.aseguradora.data,
                    workshop=form.workshop.data,
                    Fecha_Registro=datetime.utcnow()
                )
                db.session.add(new_vehicle)
            else:
                # Registrar nuevo vehículo para el cliente existente
                new_vehicle = Vehicle(
                    model=form.vehicle_model.data,
                    license_plate=form.vehicle_license_plate.data,
                    vehicle_color=form.vehicle_color.data,
                    vehicle_type=form.vehicle_type.data,
                    customer_id=customer.id,
                    aseguradora=form.aseguradora.data,
                    workshop=form.workshop.data,
                    Fecha_Registro=datetime.utcnow()
                )
                db.session.add(new_vehicle)
        else:
            flash('Cliente no encontrado. Registrando nuevo cliente y vehículo.', 'info')
            # Registrar nuevo cliente y vehículo
            customer = Customer(
                document=form.customer_document.data, 
                name=form.customer_name.data, 
                last_name=form.customer_last_name.data, 
                phone=form.customer_phone.data
            )
            db.session.add(customer)
            db.session.commit()

            new_vehicle = Vehicle(
                model=form.vehicle_model.data,
                license_plate=form.vehicle_license_plate.data,
                vehicle_color=form.vehicle_color.data,
                vehicle_type=form.vehicle_type.data,
                customer_id=customer.id,
                aseguradora=form.aseguradora.data,
                workshop=form.workshop.data,
                Fecha_Registro=datetime.utcnow()
            )
            db.session.add(new_vehicle)

        try:
            db.session.commit()
            qr_data = url_for('main.vehicle_info', vehicle_id=new_vehicle.id, _external=True)
            img = qrcode.make(qr_data)
            buf = BytesIO()
            img.save(buf)
            buf.seek(0)

            new_vehicle.qr_image = buf.getvalue()
            db.session.commit()

            qr_img_base64 = base64.b64encode(new_vehicle.qr_image).decode('utf-8')

            flash('¡Cliente y vehículo registrados exitosamente!', 'success')
        except IntegrityError:
            db.session.rollback()
            flash('Error en el registro. Por favor, intente de nuevo.', 'danger')
    else:
        flash('Por favor corrija los errores en el formulario.', 'danger')

    return render_template('register_customer.html', title='Register Customer', form=form, qr_img=qr_img_base64, customer=customer)

@main.route('/admin')
@login_required
def admin_dashboard():
    if current_user.role != 'admin':
        return redirect(url_for('main.home'))
    return render_template('admin_dashboard.html', title='Admin Dashboard')

@main.route('/admin/reports', methods=['GET', 'POST'])
@login_required
def admin_reports():
    if current_user.role != 'admin':
        return redirect(url_for('main.home'))

    # Obtener los estados distintos de la base de datos
    status = Vehicle.query.with_entities(Vehicle.status).distinct().all()
    
    # Verifica si el campo workshop existe en la base de datos
    workshops = []
    if hasattr(Vehicle, 'workshop'):
        workshops = Vehicle.query.with_entities(Vehicle.workshop).distinct().all()

    return render_template('admin_reports.html', title='Vehicle Reports', status=status, workshops=workshops)

@main.route('/get_report_data', methods=['POST'])
@login_required
def get_report_data():
    state_filter = request.json.get('state_filter', '')
    workshop_filter = request.json.get('workshop_filter', '')
    month_filter = request.json.get('month_filter', '')

    query = Vehicle.query
    if state_filter:
        query = query.filter_by(status=state_filter)
    if workshop_filter:
        query = query.filter_by(workshop=workshop_filter)
    if month_filter:
        # Suponiendo que el campo Fecha_Registro es un objeto datetime en SQLAlchemy
        query = query.filter(db.extract('month', Vehicle.Fecha_Registro) == int(month_filter))

    vehicles = query.all()

    data = {}
    for vehicle in vehicles:
        workshop = vehicle.workshop
        status = vehicle.status
        if workshop not in data:
            data[workshop] = {}
        if status in data[workshop]:
            data[workshop][status] += 1
        else:
            data[workshop][status] = 1

    print(data)  # Imprime los datos para depurar
    return jsonify(data)

@main.route('/admin/create_user', methods=['GET', 'POST'])
@login_required
def admin_create_user():
    if current_user.role != 'admin':
        return redirect(url_for('main.home'))
    form = UserRegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, role=form.role.data)
        db.session.add(user)
        db.session.commit()
        flash('¡Usuario creado exitosamente!', 'success')
        return redirect(url_for('main.admin_dashboard'))
    return render_template('admin_create_user.html', title='Create User', form=form)


FLASK/app/templates/admin_create_user.html
{% extends "base.html" %}

{% block title %}Crear Usuario{% endblock %}

{% block content %}
<h1>Create User</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.username.label }} {{ form.username(size=20) }}
    </div>
    <div>
        {{ form.email.label }} {{ form.email(size=20) }}
    </div>
    <div>
        {{ form.password.label }} {{ form.password(size=20) }}
    </div>
    <div>
        {{ form.confirm_password.label }} {{ form.confirm_password(size=20) }}
    </div>
    <div>
        {{ form.role.label }} {{ form.role() }}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
{% endblock %}

FLASK/app/templates/admin_dashboard.html
{% extends "base.html" %}

{% block title %}
Admin Dashboard
{% endblock %}

{% block content %}
<h1>Admin Dashboard</h1>
<ul>
    <li><a href="{{ url_for('main.admin_reports') }}">Reporte de Vehiculos</a></li>
    <li><a href="{{ url_for('main.admin_create_user') }}">Crear Usuarios</a></li>
    <li><a href="{{ url_for('main.admin_view_records') }}">Buscar Vehiculo</a></li>
    <li><a href="{{ url_for('main.register_customer') }}">Registrar Vehículo</a></li>
    <li><a href="{{ url_for('main.manage_user') }}">Eliminar Usuario</a></li>
</ul>
{% endblock %}

FLASK/app/templates/admin_manage_user.html
{% extends "base.html" %}

{% block title %}Eliminar Usuario{% endblock %}

{% block content %}
<h1>Eliminar Usuario</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.username.label }} {{ form.username(size=20) }}
    </div>
    <div>
        <button type="submit" name="action" value="search"
            formaction="{{ url_for('main.search_user') }}">Buscar</button>
        <button type="submit" name="action" value="delete"
            formaction="{{ url_for('main.delete_user') }}">Eliminar</button>
    </div>
</form>
{% if user_info %}
<h2>Usuario encontrado:</h2>
<p>Nombre de usuario: {{ user_info.username }}</p>
<p>Email: {{ user_info.email }}</p>
<p>Rol: {{ user_info.role }}</p>
{% endif %}
{% endblock %}

FLASK/app/templates/admin_reports.html
{% extends "base.html" %}

{% block title %}Reporte{% endblock %}

{% block content %}
<div class="report_container">
    <h1>Reportes de Vehículos</h1>
    <br>

    <canvas id="vehiclesChart" width="1200" height="600"></canvas>
    <br>

    <form id="filtersForm" class="form-group">
        <label for="state_filter">Estado:</label>
        <select id="state_filter" name="state_filter" class="form-control">
            <option value="">Todos</option>
            {% for s in status %}
            <option value="{{ s[0] }}">{{ s[0] }}</option>
            {% endfor %}
        </select>

        {% if workshops %}
        <label for="workshop_filter">Taller:</label>
        <select id="workshop_filter" name="workshop_filter" class="form-control">
            <option value="">Todos</option>
            {% for workshop in workshops %}
            <option value="{{ workshop[0] }}">{{ workshop[0] }}</option>
            {% endfor %}
        </select>
        {% endif %}

        <label for="month_filter">Mes:</label>
        <select id="month_filter" name="month_filter" class="form-control">
            <option value="">Todos</option>
            <option value="01">Enero</option>
            <option value="02">Febrero</option>
            <option value="03">Marzo</option>
            <option value="04">Abril</option>
            <option value="05">Mayo</option>
            <option value="06">Junio</option>
            <option value="07">Julio</option>
            <option value="08">Agosto</option>
            <option value="09">Septiembre</option>
            <option value="10">Octubre</option>
            <option value="11">Noviembre</option>
            <option value="12">Diciembre</option>
        </select>

        <button type="submit" class="btn btn-primary">Aplicar Filtros</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    $(document).ready(function () {
        var ctx = document.getElementById('vehiclesChart').getContext('2d');

        var colorPalette = {
            'Vehiculo en liquidación': '#ff6384',
            'Orden Aprobada': '#36a2eb',
            'Recepción de Repuestos': '#ffce56',
            'Desarme': '#4bc0c0',
            'Desabolladura': '#9966ff',
            'Levantamiento': '#ff9f40',
            'Preparación': '#f7a35c',
            'Pintura': '#50b432',
            'Ensamble': '#058dc7',
            'Brillado': '#6af9c4',
            'Lavado': '#ff6f61',
            'Terminación': '#c43a31',
            'Entrega': '#0091ea'
        };

        var vehiclesChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    },
                    x: {
                        stacked: true
                    },
                    y: {
                        stacked: true
                    }
                }
            }
        });

        function updateChart(data) {
            var workshops = Object.keys(data);
            var statuses = [...new Set(workshops.flatMap(workshop => Object.keys(data[workshop])))];

            var datasets = statuses.map(status => ({
                label: status,
                data: workshops.map(workshop => data[workshop][status] || 0),
                backgroundColor: colorPalette[status] || '#c9cbcf',
                borderColor: colorPalette[status] || '#c9cbcf',
                borderWidth: 1
            }));

            vehiclesChart.data.labels = workshops;
            vehiclesChart.data.datasets = datasets;
            vehiclesChart.update();
        }

        $('#filtersForm').on('submit', function (event) {
            event.preventDefault();
            var state_filter = $('#state_filter').val();
            var workshop_filter = $('#workshop_filter').val();
            var month_filter = $('#month_filter').val();

            $.ajax({
                url: "{{ url_for('main.get_report_data') }}",
                method: "POST",
                contentType: 'application/json',
                data: JSON.stringify({
                    state_filter: state_filter,
                    workshop_filter: workshop_filter,
                    month_filter: month_filter
                }),
                success: function (response) {
                    updateChart(response);
                }
            });
        });

        // Inicialmente cargar todos los datos
        $.ajax({
            url: "{{ url_for('main.get_report_data') }}",
            method: "POST",
            contentType: 'application/json',
            success: function (response) {
                updateChart(response);
            }
        });
    });
</script>
{% endblock %}

FLASK/app/templates/admin_view_records.html
{% extends "base.html" %}

{% block title %}View Records{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center">Buscar Vehículo</h1>
    <form method="POST" class="form-inline mb-4 mx-auto" style="max-width: 600px;">
        <div class="form-group mb-2">
            <label for="document" class="sr-only">Placa Vehículo:</label>
            <input type="text" class="form-control" id="document" name="document" placeholder="Ingrese Placa">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Buscar</button>
    </form>

    {% if vehicle %}
    <h2 class="text-center">Datos del Vehículo</h2>
    <div class="table-responsive mx-auto" style="max-width: 1200px;">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Placa</th>
                    <th scope="col">Modelo Vehículo</th>
                    <th scope="col">Color</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Taller</th>
                    <th scope="col">Aseguradora</th>
                    <th scope="col">QR</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="p-3">{{ vehicle.license_plate }}</td>
                    <td class="p-3">{{ vehicle.model }}</td>
                    <td class="p-3">{{ vehicle.vehicle_color }}</td>
                    <td class="p-3">{{ vehicle.vehicle_type }}</td>
                    <td class="p-3">{{ vehicle.workshop }}</td>
                    <td class="p-3">{{ vehicle.aseguradora }}</td>
                    <td class="p-3 text-center">
                        {% if vehicle.qr_image %}
                        <img src="data:image/png;base64,{{ base64.b64encode(vehicle.qr_image).decode('utf-8') }}"
                            alt="QR Code" class="img-fluid mb-2" style="max-width: 100px;">
                        <br>
                        <button class="btn btn-primary mt-2"
                            onclick="printQRCode('data:image/png;base64,{{ base64.b64encode(vehicle.qr_image).decode('utf-8') }}')">Imprimir
                            QR</button>
                        {% else %}
                        No QR
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>


    <form method="POST" action="{{ url_for('main.update_vehicle') }}">
        <h2 class="text-center mt-5">Editar Información del Vehículo</h2>
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.license_plate.label }} {{ form.license_plate(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.model.label }} {{ form.model(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.vehicle_color.label }} {{ form.vehicle_color(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.vehicle_type.label }} {{ form.vehicle_type(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.workshop.label }} {{ form.workshop(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.aseguradora.label }} {{ form.aseguradora(class="form-control") }}
        </div>
        <h2 class="text-center mt-5">Editar Información del Cliente</h2>
        <div class="form-group">
            {{ form.customer_document.label }} {{ form.customer_document(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.customer_name.label }} {{ form.customer_name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.customer_last_name.label }} {{ form.customer_last_name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.customer_phone.label }} {{ form.customer_phone(class="form-control") }}
        </div>
        <div class="form-group d-flex justify-content-between">
            <button type="submit" class="btn btn-success">Actualizar Información</button>
            <form method="POST" action="{{ url_for('main.delete_vehicle') }}">
                <input type="hidden" name="license_plate" value="{{ vehicle.license_plate }}">
                <button type="submit" class="btn btn-danger">Eliminar Vehículo</button>
            </form>
        </div>
    </form>
    {% endif %}
</div>

<script>
    function printQRCode(dataUrl) {
        const printWindow = window.open('', '_blank');
        printWindow.document.write('<html><head><title>Imprimir QR</title></head><body>');
        printWindow.document.write('<img src="' + dataUrl + '" style="max-width:100%;"/>');
        printWindow.document.close();
        printWindow.print();
    }
</script>
{% endblock %}

FLASK/app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
    <nav>
        {% if current_user.is_authenticated %}
        {% if current_user.role == 'operator' %}
        <a href="{{ url_for('main.register_customer') }}">Registrar Vehículo</a>
        <a href="{{ url_for('main.admin_view_records') }}">Buscar Vehículo</a>
        {% elif current_user.role == 'admin' %}
        <a href="{{ url_for('main.admin_dashboard') }}">Inicio</a>
        <a href="{{ url_for('main.admin_reports') }}">Reportes</a>
        <a href="{{ url_for('main.admin_create_user') }}">Crear Usuarios</a>
        <a href="{{ url_for('main.admin_view_records') }}">Buscar Vehículo</a>
        <a href="{{ url_for('main.register_customer') }}">Registrar Vehículo</a>
        <a href="{{ url_for('main.manage_user') }}">Eliminar Usuario</a>
        {% endif %}
        <a href="{{ url_for('main.logout') }}">Cerrar Sesión</a>
        {% else %}
        <a href="{{ url_for('main.login') }}">Login</a>
        {% endif %}
    </nav>
    <div class="content">
        {% block content %}{% endblock %}
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <span class="text-muted">&copy; {{ current_year }} App_Tecnicar. Powered by Dathink SAS, Bogotá
                Colombia</span>
        </div>
    </footer>

    {% block scripts %}{% endblock %}
</body>

</html>

FLASK/app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Bienvenido a Tecnicar Autoservices</h1>
{% endblock %}

FLASK/app/templates/login.html
{% extends "base.html" %}

{% block title %}Inicio de Sesión{% endblock %}

{% block content %}
<h1>Iniciar Sesión</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.email.label }} {{ form.email(size=20) }}
    </div>
    <div>
        {{ form.password.label }} {{ form.password(size=20) }}
    </div>
    <div>
        {{ form.remember() }} {{ form.remember.label }}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
{% endblock %}

FLASK/app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
    <h1>Register</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div>
            {{ form.username.label }} {{ form.username(size=20) }}
        </div>
        <div>
            {{ form.email.label }} {{ form.email(size=20) }}
        </div>
        <div>
            {{ form.password.label }} {{ form.password(size=20) }}
        </div>
        <div>
            {{ form.confirm_password.label }} {{ form.confirm_password(size=20) }}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
{% endblock %}

FLASK/app/templates/register_customer.html
{% extends "base.html" %}

{% block content %}
<h1>Registrar Cliente</h1>

<form method="POST" action="{{ url_for('main.register_customer') }}" id="clienteForm">
    {{ form.hidden_tag() }}
    <div>
        {{ form.customer_document.label }} {{ form.customer_document }}
    </div>
    <div>
        {{ form.customer_name.label }} {{ form.customer_name }}
    </div>
    <div>
        {{ form.customer_last_name.label }} {{ form.customer_last_name }}
    </div>
    <div>
        {{ form.customer_phone.label }} {{ form.customer_phone }}
    </div>
    <div>
        {{ form.vehicle_model.label }} {{ form.vehicle_model }}
    </div>
    <div>
        {{ form.vehicle_license_plate.label }} {{ form.vehicle_license_plate }}
    </div>
    <div>
        {{ form.vehicle_color.label }} {{ form.vehicle_color }}
    </div>
    <div>
        {{ form.vehicle_type.label }} {{ form.vehicle_type }}
    </div>
    <div>
        {{ form.aseguradora.label }} {{ form.aseguradora }}
    </div>
    <div>
        {{ form.workshop.label }} {{ form.workshop }}
    </div>
    <input type="submit" name="submit" value="Registrar" class="btn btn-primary">
</form>

{% if customer %}
<p><strong>Propietario:</strong> {{ customer.name }} {{ customer.last_name }}</p>
{% endif %}

{% if qr_img %}
<div id="qr_container" class="qr-container">
    <img src="data:image/png;base64,{{ qr_img }}" alt="QR Code">
</div>
<button id="print_qr" class="btn btn-primary">Imprimir QR</button>
{% endif %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#customer_document').on('blur', function () {
            const documento = $(this).val();
            if (documento) {
                $.ajax({
                    url: '{{ url_for("main.verificar_cliente") }}',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify({ documento: documento }),
                    success: function (response) {
                        if (response.existe) {
                            $('#customer_name').val(response.cliente.nombre);
                            $('#customer_last_name').val(response.cliente.last_name);
                            $('#customer_phone').val(response.cliente.phone);
                            // Completar otros campos del vehículo si están presentes en la respuesta
                        } else {
                            $('#customer_name').val('');
                            $('#customer_last_name').val('');
                            $('#customer_phone').val('');
                            // Limpiar otros campos del vehículo si fuera necesario
                        }
                    },
                    error: function (error) {
                        console.error('Error al verificar el cliente:', error);
                    }
                });
            }
        });

        $('#print_qr').on('click', function () {
            const printContents = document.getElementById('qr_container').innerHTML;
            const originalContents = document.body.innerHTML;
            document.body.innerHTML = printContents;
            window.print();
            document.body.innerHTML = originalContents;
            location.reload();  // Recargar la página para volver al estado original
        });
    });
</script>

{% endblock %}

FLASK/app/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
<h2>Reset Your Password</h2>
<p>An email will be sent to you with instructions on how to reset your password.</p>
<form method="POST" action="">
    {{ form.hidden_tag() }}
    {{ form.email.label }}<br>
    {{ form.email(size=32) }}<br>
    {% for error in form.email.errors %}
    <span style="color: red;">[{{ error }}]</span><br>
    {% endfor %}
    {{ form.submit() }}
</form>
{% endblock %}

FLASK/app/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
<h2>Reset Your Password</h2>
<form method="POST" action="">
    {{ form.hidden_tag() }}
    {{ form.password.label }}<br>
    {{ form.password(size=32) }}<br>
    {% for error in form.password.errors %}
    <span style="color: red;">[{{ error }}]</span><br>
    {% endfor %}
    {{ form.confirm_password.label }}<br>
    {{ form.confirm_password(size=32) }}<br>
    {% for error in form.confirm_password.errors %}
    <span style="color: red;">[{{ error }}]</span><br>
    {% endfor %}
    {{ form.submit() }}
</form>
{% endblock %}